import Navbar from "@/components/navbar";
import "./globals.css";
import { Roboto } from "next/font/google";

import Footer from "@/components/footer";

const roboto = Roboto({ weight: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "Husdyr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} min-h-screen m-0`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
